# Generated by Django 4.2.10 on 2024-02-13 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('audio_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('_length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('transcription_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(max_length=200)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elson.audio')),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elson.user'),
        ),
    ]
