# Generated by Django 5.0.2 on 2024-02-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryAudioFile',
            fields=[
                ('audiofile_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('audio_file', models.FileField(upload_to='temporary')),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(null=True, upload_to='audio/'),
        ),
    ]
