# Generated by Django 5.0.2 on 2024-02-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elson', '0002_temporaryaudiofile_audio_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryaudiofile',
            name='audio_file',
            field=models.FileField(upload_to='temporary/'),
        ),
    ]
