# Generated by Django 5.0.2 on 2024-02-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elson', '0003_alter_temporaryaudiofile_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='uid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
